### PR TITLE
Added missing creation of delta if $created

### PR DESCRIPTION
**Pull request by wewilkinson**

### CODE REVIEW

**Comment by robwilkerson** [comment]
@xhs345 : would you mind taking a look at this and either merging it or providing feedback? Thanks.

**Comment by xhs345** [comment]
@robwilkerson Will do that shortly

**Comment by xhs345** [comment]
@wewilkinson Thanks a lot for your contribution, definitely an important addition. 

One thing I noticed is that a delta is also added when the $value is empty. Could you add a check for that case?

**Comment by wewilkinson** [comment]
@xhs345 No problem, I'll take care of that.

**Comment by wewilkinson** [comment]
@xhs345 I've added the check for empty $value. I'd appreciate if you could take a look. Thanks.

**Comment by xhs345** [comment]
Thanks!

**Pull request merged**
