### PR TITLE
Do not act on the AuditLog related models

### PR DESCRIPTION
**Pull request by ravage84**
It is one way of solving #85, as mentioned there.

This still needs tests.

### CODE REVIEW

**Comment by xhs345** [comment]
I think it would be better to refactor the check `$Model->name === 'Audit' || $Model->name === 'AuditDelta'` into a separate function for easier maintainability. E.g. `isAuditLogModel`

**Comment by ravage84** [comment]
@xhs345  done, had that in mind, too.

**Comment by ravage84** [comment]
@xhs345 are you OK with the general solution or do you have a better in mind?

**Comment by xhs345** [comment]
I'm definitely happy with that solution you are providing, thanks.

**Comment by ravage84** [comment]
:cool: , you can merge this, if you are OK, when we add specifically covering tests later.

**Pull request merged**
