### PR TITLE
Replace calls to deprecated Set class with Hash

### PR DESCRIPTION
**Pull request by ravage84**
Please have a look, if my change is OK.

### CODE REVIEW

**Comment by xhs345** [comment]
Changing this would make the version incompatible with CakePHP versions before 2.2, which is something @robwilkerson tried to avoid in the past. 
You think it would be possible to load the class name conditionally (e.g. https://github.com/robwilkerson/CakePHP-Audit-Log-Plugin/pull/51/files )?

**Comment by robwilkerson** [comment]
@xhs345 I'm *way* out of touch with the Cake community and framework progress, but have 2 thoughts that you may feel free to consider or ridicule as you see fit:

1. What percentage of the install base is < v2.2? At this point, it might be a very small number that isn't really worth considering.
2. Moreover, we've always branched for lower version support while the `master` branch was focused on recent framework versions. At this point, it seems reasonable to me that the `master` branch would support v3.x. User's of v1.3 or v2.x just need to know to be sure they're working against the appropriate branch. If this would work, then backwards compatibility becomes a non-factor as long as each branch works as expected on the versions it's designated to support.

Just my thoughts, but again, you are far more qualified than I to decide the most appropriate path for the plugin. Please don't let my judgment overrule yours.

**Comment by ravage84** [comment]
@xhs345 sure I can do that.

**Comment by ravage84** [comment]
@robwilkerson CakePHP 2.x is still alive and kicking.
Since version 2.2. (which is the version I started with a few years ago, BTW), the framework has evolved. Not only into a new major release but even within the 2.x branch.
Since the rise of Composer, many plugins have been developed for 2.x and thus there is a plethora of good things to choose from for a dev using CakePHP 2.x.
Also, due to the longevity of CakePHP 2.x, many applications have been developed with it and since the CakePHP 3.x ORM makes a migration a little bit of an effort (depending ont he application), many devs have stayed with CakePHP 2.x.

So there is still a good reason to support the 2.x branch.
I agree, the 2.2. installation base might be small at this point, but as long as keeping the backwards compatibility is as easy as in this case, I think it's still worth keeping.
I try not to abandon people using old versions of my code, if it doesn't break my neck :smirk_cat: 

At the moment, there are two good solutions for creating an audit log using CakePHP 2.
1. Your plugin
2. Jippi's fork of your plugin (which incorporates FriendsOfCake CRUD views)

http://plugins.cakephp.org/packages?query=audit
https://github.com/FriendsOfCake/awesome-cakephp/tree/cake2#logging

But for CakePHP 3, there might be good alternatives already in development:
https://github.com/FriendsOfCake/awesome-cakephp/tree/master#auditing--logging

I don't say your plugin should not be upgraded to CakePHP 3, but there should be somebody to maintain it...

**Comment by robwilkerson** [comment]
I agree that the plugin only remains relevant if someone is willing to maintain it, especially given the changes you've mentioned.  So far, that's been @xhs345 and I'll let him decide how much he wants to stay involved. Of course, if it's something _you'd_ like to contribute to on any kind of a regular basis, I know we'd love the continued support and would be happy to add you as a core contributor after you have a few pull requests under your belt.

Either way, thanks for helping out with this PR.

**Comment by ravage84** [comment]
Even though I'm an active CakePHP and FOSS contributor, I'm reluctant at agreeing taking over some code maintenance, even if I wouldn't be alone, as in this case.
I'm currently evaluating auditing/data history solutions for one of my projects.
If I end up using your plugin for that project, I would have a "business interest" of this plugin keeping alive :smiley_cat:

**Comment by ravage84** [comment]
As an alternative, by the way, you could think about moving the plugin to FriendsOfCake.
But I guess there could be some clash of interest, as there is already a [fork of your plugin](https://github.com/jippi/cakephp-audit-log) of one of the [FriendsOfCake contributors](https://github.com/jippi).

**Comment by robwilkerson** [comment]
@ravage84 Understood. I understand either way. That's the beauty (and the curse) of OSS. 😀

**Comment by xhs345** [comment]
@robwilkerson Thanks for the kind words. This is still a learning process for me as well, so the feedback is appreciated. 
1. I agree. I don't feel bad for anyone who is still using a CakePHP version < 2.2 at this point and not upgrading
2. While I agree with the idea, the problem would be that the 3.x version is still in development and not 100% functional yet, so I'm a bit reluctant on this. Sadly I can't really commit much time on the 3.x development at the moment, and it's getting harder to justify for me with other working solutions out there.

@ravage84 Thanks for posting all the links. Looks like there are several other good solutions out there, that I wasn't aware of. Jippi created really good solutions for both 2.x and 3.x. 

Similar to you I'm using this Plugin for a 2.x application we developed. Overall it's working pretty well for us, so I'm just trying to do some maintenance here on the side. If you have more updates please keep them coming. Of course I would be happy if you want to contribute more.

Regarding the PR: I just noticed that the order of parameters for `SET::extract` and `HASH::extract` has changed, so my solution would probably not work as well here. As stated above and as Rob suggested, it's probably easiest to just use your changes. Will do a bit of testing next week, and then it should be all good

**Comment by ravage84** [comment]
@xhs345 the Hash class was added in CakePHP 2.2, [apparently](http://book.cakephp.org/2.0/en/appendices/2-2-migration-guide.html#hash). So there shouldn't be a big backwards incompatibility issue

**Comment by xhs345** [comment]
Ok, looks good. Thanks

**Pull request merged**
