### PR TITLE
Actual models

### PR DESCRIPTION
**Pull request by ravage84**
This adds the actual ``Audit`` & ``AuditDelta`` models.

I'm not 100 % sure if this breaks something.

But I plan to move some code from the Behavior away to the model, which will slim down the behavior (which does way too much at the moment) and fatten up the model (as it should be).

The story behind:
While working on the feature our customer wanted, I used some of this plugin's code, but moved most of it into the related model. This lead to much more readable and re-usable code.

@robwilkerson & @xhs345 I'm eager to hear your opinion.

### CODE REVIEW

**Comment by ravage84** [comment]
Also, these changes are necessary for my proposed alternative in https://github.com/robwilkerson/CakePHP-Audit-Log-Plugin/issues/39#issuecomment-247734092

**Comment by xhs345** [comment]
I really like the changes and the idea to move more code into the model

**Comment by ravage84** [comment]
Currently, the only downside of the new implementation is, that you can't set the database to use for the models.

We could make it configurable thorugh a ``Configure`` key like ``App.AuditLog.database``.
Refers to https://github.com/robwilkerson/CakePHP-Audit-Log-Plugin/issues/29#issuecomment-49775835.

**Comment by xhs345** [comment]
Yes, that would be a good addition

**Comment by xhs345** [comment]
I worked without problems in our application. The merge should make it easier to make further modifications

**Pull request merged**
