### PR TITLE
Fix behavior so that it audits softdeletes

### PR DESCRIPTION
**Pull request by inigoflores**
If no record is found in afterSave(), it is assumed it is due to a delete operation under a soft-delete behavior. The audit is then treated as a delete and $this->afterDelete($Model) is called. Let me know if this makes sense.

Also fixed the deprecated String error.

### CODE REVIEW

**Comment by robwilkerson** [comment]
Okay, sounds like you've fixed #41, right? If that's the case, would you either double check that the CakeText fix also works in 2.6 or, alternatively, have your fix make a quick check before using the right one? I'd really like the 1 `2.x` branch to be compatible with all 2.x versions of Cake.

Thanks again for improving the project.

**Comment by inigoflores** [comment]
I'm looking into setting up Travis CI to be able to test other CakePHP versions. I'll get back to you when I've figured it out.

**Comment by robwilkerson** [comment]
Fantastic! Let me know what you find. I'd love to have better (read: some) test coverage behind this.

**Comment by inigoflores** [comment]
Merged #48 and then added composer.json & Readme stuff.

See it it's OK.

**Comment by xhs345** [comment]
@robwilkerson I'm not sure what the status is for this pull-request. Anything you wanted to check / test before merging?

**Comment by robwilkerson** [comment]
I'm good if you're good.

On April 28, 2016 at 1:44:39 PM, Alex (notifications@github.com) wrote:

> @robwilkerson <https://github.com/robwilkerson> I'm not sure what the
> status is for this pull-request. Anything you wanted to check / test before
> merging?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/robwilkerson/CakePHP-Audit-Log-Plugin/pull/45#issuecomment-215507184>
>

# Rob Wilkerson
# @robwilkerson

**Comment by xhs345** [comment]
Sorry, took me some time to do some testing myself. I added SoftDelete to one of my own projects and it seems to be working fine.

@inigoflores Thanks for your contribution!

**Comment by inigoflores** [comment]
Great! I'm glad it helped!

**Pull request merged**
