### PR TITLE
Create composer.json

### PR DESCRIPTION
**Pull request by inigoflores**
Hi

I've created a composer.json file to enable the install through `composer`.

Thanks

### CODE REVIEW

**Comment by robwilkerson** [comment]
This is great, @inigoflores ! Thanks. Would you mind updating the **Installation** section of the README to reflect this capability? Add a **Using Composer** section beneath **As a Submodule** that specifies the command to be used.

Once that's complete, I'll merge both commits. Thanks for improving the plugin.

**Comment by inigoflores** [comment]
Great! However, for this to work out of the box, the package needs to be published to Packagist. And before this may happen, the composer.json file needs to be present in the github repository.

Without packagist, you have to manually define a git repository in app/composer.json.
```
     {
        "repositories": [
            {
                "url": "git@github.com:robwilkerson/CakePHP-Audit-Log-Plugin.git",
                "type": "git"
            }
        ],
        "require": {
            "robwilkerson/CakePHP-Audit-Log-Plugin": "dev-master"
    }
```
However, it's a bit of a hassle. 

Before publishing to packagist, it may be a good opportunity to create the 2.x branch. The master branch may turn 3.x in the future.

Let me have your thoughts.

**Comment by robwilkerson** [comment]
Is the Composer install specific to v2.x? Seems like that would work either way, no?

**Comment by inigoflores** [comment]
Yes, but to publish to packagist you must chose which branch you want to track. Let me fix the composer.json, now that 2.x has been created.

**Comment by inigoflores** [comment]
Sorry, my mistake. Packagist will package all branches, and you chose the right one in /app/composer.json.

I'm reopening the pull request. 

Perhaps you want to publish the package yourself from your own packagist account?

**Comment by robwilkerson** [comment]
@inigoflores First, please update the README on the `2.x` branch and include that change in this pull request. Also, as far as I'm concerned, this is your effort so I have no problem with it going under your Packagist account. 

Also, since I've done so little Cake (or PHP) work recently, it would probably have a better chance of staying current if you manage it. :-)

**Comment by inigoflores** [comment]
Sorry for the late reply. I've been rather busy!

I've modified the Readme. See if it's OK. 

However, the instructions won't work until I publish the package, and before it can be published, the `composer.json` file must exist in the repository. 

This is for master. The 2.x branch will need `dev-master` replaced with  `dev-2.x`:

		    "robwilkerson/CakePHP-Audit-Log-Plugin": "dev-2.x"

As soon as you do the merge, I will publish the package.

**Pull request merged**
